import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const fontPoppins = Poppins ({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
})

export const metadata = {
  title: "Neuro Luka",
  description: "Generated by Neuro Luka Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontPoppins.className}  antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
