import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import 'remixicon/fonts/remixicon.css'
import Hero from "@/components/Hero";
import Sosmed from "@/components/Sosmed";
import About from "@/components/About";

const fontPoppins = Poppins ({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
})

export const metadata = {
  title: "Neuro Luka",
  description: "Generated by Neuro Luka Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.className}  antialiased`}
      >
        <Navbar />
        <Hero />
        <Sosmed />
        <About />
        <div className="container mx-auto px-4">
        {children}
        </div>
        
      </body>
    </html>
  );
}
